check50:
  files:
    - !require ex1.py
    - !require ex2.py
  checks:
    ex1:
      - run: python3 ex1.py
        stdout: 68640
        exit: 0
    ex2:
      - run: python3 ex2.py
        stdout: 26497

submit50:
  files: *check50_files